CREATE TABLE `trades` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`ext_id` INT(11) NULL DEFAULT '0',
	`date` DATETIME NULL DEFAULT NULL,
	`market` VARCHAR(120) NULL DEFAULT '0',
	`exchange` VARCHAR(120) NULL DEFAULT '0',
	`quantity` DOUBLE NULL DEFAULT '0',
	`price` DOUBLE NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
ENGINE=InnoDB
;

CREATE TABLE `strategy` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NULL DEFAULT null,
	`language` VARCHAR(50) NULL DEFAULT 'javascript',
	`script` MEDIUMTEXT NULL DEFAULT NULL,
	`version` INT(11) NULL DEFAULT '1',
	PRIMARY KEY (`id`)
)
ENGINE=InnoDB
;

CREATE TABLE `candle` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`period` VARCHAR(5) NOT NULL DEFAULT '1min',
	`exchange` VARCHAR(120) NOT NULL,
	`market` VARCHAR(120) NOT NULL,
	`start` DATETIME NOT NULL,
	`end` DATETIME NOT NULL,
	`open` DOUBLE NULL DEFAULT '0',
	`high` DOUBLE NULL DEFAULT '0',
	`low` DOUBLE NULL DEFAULT '0',
	`close` DOUBLE NULL DEFAULT '0',
	`volume` DOUBLE NULL DEFAULT '0',
	`price` DOUBLE NULL DEFAULT '0',
	`trade_count` INT(11) NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
ENGINE=InnoDB
;