CREATE TABLE `trades` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`ext_id` INT(11) NULL DEFAULT '0',
	`date` DATETIME NULL DEFAULT NULL,
	`market` VARCHAR(120) NULL DEFAULT '0',
	`exchange` VARCHAR(120) NULL DEFAULT '0',
	`quantity` DOUBLE NULL DEFAULT '0',
	`price` DOUBLE NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
ENGINE=InnoDB
;